RADIUMFRONT-12: Recover styles of buttons
radium-rtf/radium-frontend pull request #30
Opened 2024-04-19 11:53 UTC by Reyney91

2024-04-19 12:34 UTC, Hariz0n commented on src/entities/Answers/ui/checkAnswerSection.tsx
> +    if ('data' in response) {
Вроде если как ты сделать, то TS будет ругаться

2024-04-19 12:43 UTC, Hariz0n requested changes

2024-04-19 12:43 UTC, Hariz0n commented on src/entities/Answers/model/answersSchema.ts
> +  score: z.preprocess(
А зачем тут preprocess? Хватило бы просто number, и в аргументы передать текст ошибки

2024-04-19 12:43 UTC, Hariz0n commented on src/entities/Answers/ui/checkAnswerSection.tsx
> +                отправлено {sentDate.getDay()} {monthDictionary[sentDate.getMonth()]}{' '}
getDay возвращает день недели, а не день месяца. Для второго надо использовать getDate

2024-04-20 09:39 UTC, Reyney91 commented on src/entities/Answers/ui/checkAnswerSection.tsx
> +    if ('data' in response) {
Да, ts не даст)

2024-04-22 14:16 UTC, Hariz0n approved these changes

2024-04-22 14:16 UTC, merged