Feature/input file
radium-rtf/radium-frontend pull request #7
Opened 2023-10-03 19:26 UTC by Arista213

2023-10-04 06:52 UTC, Hariz0n requested changes
Не хватает ограничений по весу файла и по расширению.

Также не сделал реекспорт из index.ts файла в shared папке

2023-10-13 06:37 UTC, Hariz0n reviewed
Все ок, только зачем были созданы компоненты close и download button

2023-10-13 06:37 UTC, Hariz0n commented on src/shared/ui/DownloadButton.tsx
> +    const handleDownload = () => {
Не проще сделать просто <a> тег с атрибутом download и передать ссылку на файл. Тогда этот хендлер и не нужен будет

2023-10-13 06:37 UTC, Hariz0n commented on src/shared/ui/CloseButton.tsx
> +    className = "w-6 h-6 p-1 hover:bg-text-primary hover:bg-opacity-10",
Почему на задать дефолтные и новые стили в самой компонент (с помощью cn())?

2023-10-13 06:37 UTC, Hariz0n commented on src/shared/hooks/useDrop.ts
> +    const preventDefault = useCallback((event: { preventDefault: () => void; stopPropagation: () => void; }) => {
Тут можно event сделать типом Event, как это сделано ниже

2023-10-13 06:37 UTC, Hariz0n commented on src/shared/ui/InputFile.tsx
> +                    'text-text-primary': file,
Лучше сделать так: isAttachError && 'styles'
Или так: isAttachError && [style1, style2]

2023-10-13 06:37 UTC, Hariz0n commented on src/shared/ui/DownloadButton.tsx
> +'use client'
Есть ли смысл от компонент CloseButton и DownloadButton?

2023-10-13 09:38 UTC, Arista213 commented
> Все ок, только зачем были созданы компоненты close и download button

CloseButton я просто решил вынести из InputFile.ts, чтобы проще читать было. Еще я хотел сделать реализацию InputFile с кнопкой загрузки, но туда это плохо ложиться. Так как кнопку загрузки я сделал, то решил оставить

2023-10-13 09:45 UTC, Arista213 commented on src/shared/ui/CloseButton.tsx
> +    className = "w-6 h-6 p-1 hover:bg-text-primary hover:bg-opacity-10",
Сделал аргумент className в конце cn(), чтобы можно было переопределить стиль

2023-10-13 09:50 UTC, Arista213 commented on src/shared/ui/InputFile.tsx
> +                    'text-text-primary': file,
Сделал

2023-10-13 09:51 UTC, Hariz0n approved these changes

2023-10-13 10:39 UTC, merged